-- MySQL Script generated by MySQL Workbench
-- 10/15/18 17:15:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sistema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sistema` ;

-- -----------------------------------------------------
-- Table `sistema`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`empresas` (
  `id_user` VARCHAR(45) NULL COMMENT '',
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(75) NOT NULL COMMENT '',
  `categoria` VARCHAR(45) NOT NULL COMMENT '',
  `telefone` VARCHAR(9) NOT NULL COMMENT '',
  `cnpj` VARCHAR(14) NOT NULL COMMENT '',
  `logradouro` VARCHAR(50) NOT NULL COMMENT '',
  `complemento` VARCHAR(15) NOT NULL COMMENT '',
  `bairro` VARCHAR(55) NOT NULL COMMENT '',
  `cidade` VARCHAR(45) NOT NULL COMMENT '',
  `uf` VARCHAR(2) NOT NULL COMMENT '',
  `descricao` VARCHAR(150) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `sistema`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema`.`usuarios` (
  `id_user` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(60) NOT NULL COMMENT '',
  `email` VARCHAR(360) NOT NULL COMMENT '',
  `senha` VARCHAR(150) NOT NULL COMMENT '',
  PRIMARY KEY (`id_user`)  COMMENT '',
  UNIQUE INDEX `id_user` (`id_user` ASC)  COMMENT '',
  CONSTRAINT `id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `sistema`.`empresas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
